coverage:
  precision: 2
  round: nearest
  range: "60...100"
  ignore:
  - IBKitTests/*
  - IBDemo/*
  - Pods/*
  - IBKit/ThirdParties/*    
  - IBKit/Categories/*   
 
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
